// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful'
import { Document } from '@contentful/rich-text-types'

export interface IMainFields {
  /** Title */
  title?: string | undefined

  /** Subtitle */
  subtitle?: string | undefined

  /** Description */
  description?: Document | undefined
}

/** Main information of website */

export interface IMain extends Entry<IMainFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'main'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ISkillFields {
  /** Skill */
  skill?: string | undefined
}

export interface ISkill extends Entry<ISkillFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'skill'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ISkillListFields {
  /** Title */
  title?: string | undefined

  /** Skill List */
  skillList?: ISkill[] | undefined
}

export interface ISkillList extends Entry<ISkillListFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'skillList'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ITagsFields {
  /** Tag */
  tag?: string | undefined
}

export interface ITags extends Entry<ITagsFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'tags'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IWorkPieceFields {
  /** Title */
  title?: string | undefined

  /** Description */
  description?: Document | undefined

  /** Image */
  image?: Asset[] | undefined

  /** Related Skills */
  relatedSkills?: ISkill[] | undefined

  /** Tags */
  tags?: ITags[] | undefined
}

/** Work Piece */

export interface IWorkPiece extends Entry<IWorkPieceFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'workPiece'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE = 'main' | 'skill' | 'skillList' | 'tags' | 'workPiece'

export type LOCALE_CODE = 'en-US' | 'pt-BR'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
