import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useAppDispatch, useAppSelector } from '../app/hooks'
import {
  setLight,
  setDark,
  selectThemeSwitcher,
} from '../features/themeSwitcher/themeSwitcherSlice'

const Home: NextPage = () => {
  const dispatch = useAppDispatch()
  const theme = useAppSelector(selectThemeSwitcher)

  const handleClick = () => {
    if (theme == 'dark') {
      dispatch(setLight())
    } else {
      dispatch(setDark())
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button onClick={handleClick}>Click here</button>
        <p>{theme}</p>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  )
}

export default Home
